node('nodejs') {
  stage('build') {
    openshiftBuild(buildConfig: 'nodejs-ex', showBuildLogs: 'true')
  }

  parallel(
    bayesianSonar: {
      stage('trigger Bayesian scan') {
        def scannerHome = tool 'SonarQube Scanner 2.8';
        
        // lets run a analysis
        withSonarQubeEnv('ACME SonarQube Bayesian') {
            sh "${scannerHome}/bin/sonar-scanner"
        }
      }
    },
    deploy: {
      stage('deploy') {
        openshiftDeploy(deploymentConfig: 'nodejs-ex')
      }
    }
  )

}
